<?php
  $paymentMethod = Mage::getModel('ravecheckout/paymentMethod');
  $pbkey = $paymentMethod->getConfigData('public_key');
  $title = $paymentMethod->getConfigData('modal_title');
  $desc = $paymentMethod->getConfigData('modal_desc');
  $currency = $paymentMethod->getConfigData('currency');
  $country = $paymentMethod->getConfigData('country');
  $logo = $paymentMethod->getConfigData('logo');
  $base_url = $paymentMethod->getBaseUrl();

  $order = Mage::getSingleton('ravecheckout/order')->getOrder();

  $amount = $order->getGrandTotal();
  $customer = $order->getCustomerEmail();
  $orderId = $order->getId();

  $amount = $order->getGrandTotal();
  $customer = $order->getCustomerEmail();

  $cartUrl = Mage::getUrl('checkout/cart', array('_secure' => false));

?>

<script type="text/javascript" defer=true>
  //<![CDATA[

  var processed = false;
  var orderExists = '<?php echo isset($orderId) ?>';

  var buildConfig = function() {
    return {
      amount: '<?php echo $amount; ?>',
      country: '<?php echo $country; ?>',
      currency: '<?php echo $currency; ?>',
      custom_description: '<?php echo $desc; ?>',
      custom_logo: '<?php echo $logo ?>',
      custom_title: '<?php echo $title; ?>',
      customer_email: '<?php echo $customer; ?>',
      PBFPubKey: '<?php echo $pbkey; ?>',
      txref: '<?php echo "MAGE1_" . $orderId . "_" . time() ?>',
      onclose: function() {
        if ( localStorage.reviewSaved && ! processed ) {
          processed = true;
          var h2 = document.getElementById('status-text');
          var button = createDOMElement('button', {id: 'pay-button', class: 'button'});
          var h2Container = h2.parentNode;

          h2.innerHTML = 'Payment has not been received';
          button.innerHTML = 'PAY NOW';
          h2Container.appendChild(button);

          button.addEventListener('click', function() {
            processPayment();
          });
        }
      },
      callback: function(res) {
        sendOrderResponse(res);
      }
    };
  };

  var sendOrderResponse = function(res) {
    processed = true;
    var data = res.tx,
        args = {
          responseCode: ( data.paymentType === 'account' ) ? data.acctvalrespcode : data.vbvrespcode,
          txRef: data.txRef,
          orderId: '<?php echo $orderId; ?>'
        };
    submitOrderForm(args);
  };

  var submitOrderForm = function(data) {
    var form = createDOMElement( 'form', {method: 'post', action: "<?php echo Mage::helper('ravecheckout')->getPaymentProcessUrl(); ?>" } );
    form.appendChild(createDOMElement('input', {name: 'txRef', value: data.txRef}));
    delete localStorage.reviewSaved;
    form.style.display = "";
    document.body.appendChild(form);
    form.submit();
  };


  var processPayment = function() {
    if (orderExists === '1') {
      var config = buildConfig();
      getpaidSetup(config);
    } else {
      location.href = '<?php echo $cartUrl; ?>';
    }
  };

  /** Creates element to be attached to the DOM */
  var createDOMElement = function(type, attrObj) {
    var elementAttr = attrObj || {};
    var element = document.createElement(type);

    if (Object.keys(elementAttr).length > 0) {
      for( var attr in elementAttr) {
        if (elementAttr.hasOwnProperty(attr)) {
          element.setAttribute( attr, elementAttr[attr] );
        }
      }
    }

    return element;
  };

  if ( localStorage.reviewSaved && ! processed ) {
    setTimeout(function(){ processPayment(); }, 500);
  }
  else {
    location.href = '<?php echo $cartUrl; ?>';
  }

//]]>
</script>

<h1>Your order is pending.</h1>
<h2 id="status-text">Loading payment gateway...</h2>
