<script type="text/javascript">
  document.getElementById('rave_place_order_button')
          .addEventListener('click', function(evt) {
            localStorage.reviewSaved = 'true';
            review.save();
          });
</script>
<button
  id="rave_place_order_button"
  type="submit"
  title="<?php echo Mage::helper('core')->quoteEscape($this->__('Order with Rave')) ?>"
  class="button btn-checkout"
>
  <span>
    <span>
      <?php echo $this->__('Order with Rave') ?>
    </span>
  </span>
</button>

